# This script generates a .htaccess file for content negotiation according to the 
# W3C Best Practice Recipes for Publishing RDF Vocabularies recipe4a
# https://www.w3.org/TR/swbp-vocab-pub/#recipe4a
# Some commented-out code from their example .htaccess file may persist here.
#
# The following command line parameters are substituted into the generated file.
$rewrite_base, $vocab_url_suffix, $vocab_rdf, $html_file = ARGV

$nargs = 4
raise "#{$0}: Wrong number of command line parameters. expected #{$nargs}." unless ARGV.size == $nargs

# CAUTION: Be really careful about escaping hashes that are intended to end up in a rewritten URL!
#          Also the NE (no excape) part of [R=303,NE] is vital, or you end up with %23 in the URL instad of #.

puts <<-HERE
# This .htaccess file was generated by #{$0} with parameters:
#    rewrite_base: #{$rewrite_base}
#    vocab_url_suffix: #{$vocab_url_suffix}
#    vocab_rdf: #{$vocab_rdf}
#    html_file: #{$html_file}
#
# Turn off MultiViews
Options -MultiViews

# Directive to ensure *.rdf files served as appropriate content type,
# if not present in main apache config
AddType application/rdf+xml .rdf

# Rewrite engine setup
RewriteEngine On
#RewriteBase /examples
RewriteBase #{$rewrite_base}

# For debugging. See Logging section in http://httpd.apache.org/docs/current/mod/mod_rewrite.html
# BUT ... LogLevel must be done in apache config file, not allowed in .htaccess.
# LogLevel alert rewrite:trace3

# Rewrite rule to serve HTML content from the namespace URI if requested
RewriteCond %{HTTP_ACCEPT} !application/rdf\+xml.*(text/html|application/xhtml\+xml)
RewriteCond %{HTTP_ACCEPT} text/html [OR]
RewriteCond %{HTTP_ACCEPT} application/xhtml\+xml [OR]
RewriteCond %{HTTP_USER_AGENT} ^Mozilla/.*
#RewriteRule ^example4a/$ example4a-content/2005-10-31.html [R=303]
RewriteRule ^#{$vocab_url_suffix}/$ #{$html_file} [R=303]

# Rewrite rule to serve directed HTML content from class/prop URIs
RewriteCond %{HTTP_ACCEPT} !application/rdf\+xml.*(text/html|application/xhtml\+xml)
RewriteCond %{HTTP_ACCEPT} text/html [OR]
RewriteCond %{HTTP_ACCEPT} application/xhtml\+xml [OR]
RewriteCond %{HTTP_USER_AGENT} ^Mozilla/.*
#RewriteRule ^example4a/(.+) example4a-content/2005-10-31.html\#$1 [R=303,NE]
RewriteRule ^#{$vocab_url_suffix}/(.+) #{$html_file}\#$1 [R=303,NE]

# Rewrite rule to serve RDF/XML content from the namespace URI by default
#RewriteRule ^example4a/ example4a-content/2005-10-31.rdf [R=303]
RewriteRule ^#{$vocab_url_suffix}/ #{$vocab_rdf} [R=303]
HERE
